### ISSUE TITLE
Tagging errors for "so"

### ISSUE THREAD

**Issue by muchang** [UniversalDependencies/UD_English-GUM#24] opened 2021-07-10 16:36 UTC
In GUM, some "so"s should be tagged as "SCONJ" while they are tagged as "ADV". For example, 
```
# sent_id = GUM_whow_basil-17
# s_type = decl
# text = Basil needs warm air and sun to do well, so it's often easiest to start the seeds indoors instead of risking that they'll get damaged by frost.
1	Basil	basil	NOUN	NN	Number=Sing	2	nsubj	2:nsubj	Discourse=solutionhood:43->45|Entity=(plant-1)
2	needs	need	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	0:root	_
3	warm	warm	ADJ	JJ	Degree=Pos	4	amod	4:amod	Entity=(abstract-46
4	air	air	NOUN	NN	Number=Sing	2	obj	2:obj	_
5	and	and	CCONJ	CC	_	6	cc	6:cc	_
6	sun	sun	NOUN	NN	Number=Sing	4	conj	2:obj|4:conj:and	Entity=abstract-46)
7	to	to	PART	TO	_	8	mark	8:mark	Discourse=purpose:44->43
8	do	do	VERB	VB	VerbForm=Inf	2	advcl	2:advcl:to	_
9	well	well	ADV	RB	Degree=Pos	8	advmod	8:advmod	SpaceAfter=No
10	,	,	PUNCT	,	_	11	punct	11:punct	_
11	so	so	ADV	RB	_	2	advmod	2:advmod	Discourse=motivation:45->42
12-13	it's	_	_	_	_	_	_	_	_
12	it	it	PRON	PRP	Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs	15	expl	15:expl	Entity=(event-47)
13	's	be	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	15	cop	15:cop	_
14	often	often	ADV	RB	Degree=Pos	15	advmod	15:advmod	_
15	easiest	easy	ADJ	JJS	Degree=Sup	2	parataxis	2:parataxis	_
16	to	to	PART	TO	_	17	mark	17:mark	Entity=(event-47
17	start	start	VERB	VB	VerbForm=Inf	15	csubj	15:csubj	_
18	the	the	DET	DT	Definite=Def|PronType=Art	19	det	19:det	Entity=(plant-43
19	seeds	seed	NOUN	NNS	Number=Plur	17	obj	17:obj	Entity=plant-43)
20	indoors	indoors	ADV	RB	Degree=Pos	17	advmod	17:advmod	Entity=event-47)
21	instead	instead	ADV	RB	Degree=Pos	23	advmod	23:advmod	Discourse=antithesis:46->45
22	of	of	SCONJ	IN	_	23	mark	23:mark	_
23	risking	risk	VERB	VBG	VerbForm=Ger	17	advcl	17:advcl:of	_
24	that	that	SCONJ	IN	_	28	mark	28:mark	_
25-26	they'll	_	_	_	_	_	_	_	_
25	they	they	PRON	PRP	Case=Nom|Number=Plur|Person=3|PronType=Prs	28	nsubj:pass	28:nsubj:pass	Entity=(plant-43)
26	'll	will	AUX	MD	VerbForm=Fin	28	aux	28:aux	_
27	get	get	AUX	VB	VerbForm=Inf	28	aux:pass	28:aux:pass	_
28	damaged	damage	VERB	VBN	Tense=Past|VerbForm=Part|Voice=Pass	23	ccomp	23:ccomp	_
29	by	by	ADP	IN	_	30	case	30:case	_
30	frost	frost	NOUN	NN	Number=Sing	28	obl	28:obl:by	Entity=(event-48)|SpaceAfter=No
31	.	.	PUNCT	.	_	2	punct	2:punct	_
```
```
# sent_id = GUM_whow_basil-37
# s_type = multiple
# text = Basil does not tolerate frost so don't plant too early.
1	Basil	basil	NOUN	NN	Number=Sing	4	nsubj	4:nsubj	Discourse=motivation:82->83|Entity=(plant-1)
2	does	do	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	4	aux	4:aux	_
3	not	not	PART	RB	Polarity=Neg	4	advmod	4:advmod	_
4	tolerate	tolerate	VERB	VB	VerbForm=Inf	0	root	0:root	_
5	frost	frost	NOUN	NN	Number=Sing	4	obj	4:obj	Entity=(event-48)
6	so	so	ADV	RB	_	9	advmod	9:advmod	Discourse=elaboration:83->81
7-8	don't	_	_	_	_	_	_	_	_
7	do	do	AUX	VB	VerbForm=Inf	9	aux	9:aux	_
8	n't	not	PART	RB	Polarity=Neg	9	advmod	9:advmod	_
9	plant	plant	VERB	VB	Mood=Imp|Person=2|VerbForm=Fin	4	parataxis	4:parataxis	_
10	too	too	ADV	RB	Degree=Pos	11	advmod	11:advmod	_
11	early	early	ADJ	JJ	Degree=Pos	9	xcomp	9:xcomp	SpaceAfter=No
12	.	.	PUNCT	.	_	4	punct	4:punct	_
```
```
# sent_id = GUM_whow_flirt-9
# s_type = decl
# text = The hardest part of flirting is to break through your initial reluctance, so if you're having a hard time taking the plunge, just remind yourself that no matter how badly it goes, it'll be less stressful than an equivalent real-world encounter.
1	The	the	DET	DT	Definite=Def|PronType=Art	3	det	3:det	Discourse=evaluation:20->16|Entity=(abstract-27
2	hardest	hard	ADJ	JJS	Degree=Sup	3	amod	3:amod	_
3	part	part	NOUN	NN	Number=Sing	8	nsubj	8:nsubj	_
4	of	of	SCONJ	IN	_	5	mark	5:mark	_
5	flirting	flirt	VERB	VBG	VerbForm=Ger	3	advcl	3:advcl:of	Entity=(event-17)abstract-27)
6	is	be	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	8	cop	8:cop	_
7	to	to	PART	TO	_	8	mark	8:mark	_
8	break	break	VERB	VB	VerbForm=Inf	0	root	0:root	_
9	through	through	ADP	IN	_	12	case	12:case	_
10	your	your	PRON	PRP$	Person=2|Poss=Yes|PronType=Prs	12	nmod:poss	12:nmod:poss	Entity=(event-28(person-2)
11	initial	initial	ADJ	JJ	Degree=Pos	12	amod	12:amod	_
12	reluctance	reluctance	NOUN	NN	Number=Sing	8	obl	8:obl:through	Entity=event-28)|SpaceAfter=No
13	,	,	PUNCT	,	_	18	punct	18:punct	_
14	so	so	ADV	RB	_	18	dep	18:dep	Discourse=concession:21->25
15	if	if	SCONJ	IN	_	18	mark	18:mark	Discourse=condition:22->24
16	you	you	PRON	PRP	Case=Nom|Number=Sing|Person=2|PronType=Prs	18	nsubj	18:nsubj	Entity=(person-2)|SpaceAfter=No
17	're	be	AUX	VBP	Mood=Ind|Number=Sing|Person=2|Tense=Pres|VerbForm=Fin	18	cop	18:cop	_
18	having	have	VERB	VBG	VerbForm=Ger	8	parataxis	8:parataxis	_
19	a	a	DET	DT	Definite=Ind|PronType=Art	21	det	21:det	Entity=(abstract-29
20	hard	hard	ADJ	JJ	Degree=Pos	21	amod	21:amod	_
21	time	time	NOUN	NN	Number=Sing	18	obj	18:obj	_
22	taking	take	VERB	VBG	VerbForm=Ger	21	acl	21:acl	Discourse=circumstance:23->22
23	the	the	DET	DT	Definite=Def|PronType=Art	24	det	24:det	Entity=(event-30
24	plunge	plunge	NOUN	NN	Number=Sing	22	obj	22:obj	Entity=abstract-29)event-30)|SpaceAfter=No
25	,	,	PUNCT	,	_	27	punct	27:punct	Discourse=same-unit:24->21
26	just	just	ADV	RB	_	27	advmod	27:advmod	_
27	remind	remind	VERB	VB	VerbForm=Inf	18	advcl	18:advcl	_
28	yourself	yourself	PRON	PRP	Case=Acc|Number=Sing|Person=2|PronType=Prs|Reflex=Yes	27	obj	27:obj	Entity=(person-2)
29	that	that	SCONJ	IN	_	41	mark	41:mark	_
30	no	no	DET	DT	Polarity=Neg	31	det	31:det	_
31	matter	matter	NOUN	NN	Number=Sing	35	obl:npmod	35:obl:npmod	_
32	how	how	SCONJ	WRB	PronType=Int	33	mark	33:mark	_
33	badly	badly	ADV	RB	Degree=Pos	35	advmod	35:advmod	_
34	it	it	PRON	PRP	Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs	35	nsubj	35:nsubj	Entity=(event-17)
35	goes	go	VERB	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	41	advcl	41:advcl	SpaceAfter=No
36	,	,	PUNCT	,	_	35	punct	35:punct	_
37-38	it'll	_	_	_	_	_	_	_	_
37	it	it	PRON	PRP	Case=Nom|Gender=Neut|Number=Sing|Person=3|PronType=Prs	41	nsubj	41:nsubj	Discourse=motivation:25->16|Entity=(event-17)
38	'll	will	AUX	MD	VerbForm=Fin	41	aux	41:aux	_
39	be	be	AUX	VB	VerbForm=Inf	41	cop	41:cop	_
40	less	less	ADV	RBR	Degree=Cmp	41	advmod	41:advmod	_
41	stressful	stressful	ADJ	JJ	Degree=Pos	27	ccomp	27:ccomp	_
42	than	than	ADP	IN	_	46	case	46:case	_
43	an	a	DET	DT	Definite=Ind|PronType=Art	46	det	46:det	Entity=(event-31
44	equivalent	equivalent	ADJ	JJ	Degree=Pos	46	amod	46:amod	_
45	real-world	real	NOUN	NN	Number=Sing	46	compound	46:compound	Entity=(place-20)
46	encounter	encounter	NOUN	NN	Number=Sing	41	obl	41:obl:than	Entity=event-31)|SpaceAfter=No
47	.	.	PUNCT	.	_	8	punct	8:punct	_
```
Commit: d38df82

**Comment by nschneid** [comment] 2021-07-10 17:02
I think this is as intended: SCONJ for "so (that)" uses and ADV for "so" when it means 'therefore'.

**Comment by youyusama** [comment] 2021-07-11 07:07
That's a concise and convincing explanation, Nathan. I agree with this view, and I have also noticed that some "so" tag have been corrected from "SCONJ" to "ADV" in one commit. 25157b34b5eee5c5542ba3410b9e06b821bbd4d9
But I still found some tagging errors of the "so" tag in the latest version. Are they the missed cases?
For example, in the following two sentences, I think "so" means "therefore" while they are tagged as  SCONJ.
```
# sent_id = GUM_fiction_veronique-29
# s_type = decl
# text = I didn't understand so I didn't say anything.
1	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	4	nsubj	4:nsubj	Discourse=cause:54->55|Entity=(person-3)
2-3	didn't	_	_	_	_	_	_	_	_
2	did	do	AUX	VBD	Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin	4	aux	4:aux	_
3	n't	not	PART	RB	Polarity=Neg	4	advmod	4:advmod	_
4	understand	understand	VERB	VB	VerbForm=Inf	0	root	0:root	_
5	so	so	SCONJ	IN	_	9	mark	9:mark	Discourse=evaluation:55->49
6	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	9	nsubj	9:nsubj	Entity=(person-3)
7-8	didn't	_	_	_	_	_	_	_	_
7	did	do	AUX	VBD	Mood=Ind|Number=Sing|Person=1|Tense=Past|VerbForm=Fin	9	aux	9:aux	_
8	n't	not	PART	RB	Polarity=Neg	9	advmod	9:advmod	_
9	say	say	VERB	VB	VerbForm=Inf	4	advcl	4:advcl:so	_
10	anything	anything	NOUN	NN	Number=Sing	9	obj	9:obj	Entity=(abstract-26)|SpaceAfter=No
11	.	.	PUNCT	.	_	4	punct	4:punct	_
```
```
# sent_id = GUM_vlog_lipstick-126
# s_type = decl
# speaker = AlyssaMarie
# text = I've definitely had this over two years though so I'm just gonna go ahead and throw it in the expired pile.
1-2	I've	_	_	_	_	_	_	_	_
1	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	4	nsubj	4:nsubj	Discourse=justify:174->176|Entity=(person-21)
2	've	have	AUX	VBP	Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin	4	aux	4:aux	_
3	definitely	definitely	ADV	RB	Degree=Pos	4	advmod	4:advmod	_
4	had	have	VERB	VBN	Tense=Past|VerbForm=Part	0	root	0:root	_
5	this	this	PRON	DT	Number=Sing|PronType=Dem	4	obj	4:obj	Entity=(object-86)
6	over	over	ADV	RB	_	7	advmod	7:advmod	Entity=(time-90
7	two	two	NUM	CD	NumForm=Word|NumType=Card	8	nummod	8:nummod	_
8	years	year	NOUN	NNS	Number=Plur	4	obl:tmod	4:obl:tmod	Entity=time-90)
9	though	though	ADV	RB	Degree=Pos	4	advmod	4:advmod	_
10	so	so	SCONJ	RB	_	14	mark	14:mark	Discourse=preparation:175->176
11-12	I'm	_	_	_	_	_	_	_	_
11	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	14	nsubj	14:nsubj|16:nsubj:xsubj|19:nsubj:xsubj	Entity=(person-21)
12	'm	be	AUX	VBP	Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin	14	aux	14:aux	_
13	just	just	ADV	RB	_	14	advmod	14:advmod	_
14-15	gonna	_	_	_	_	_	_	_	_
14	gon	go	VERB	VBG	Tense=Pres|VerbForm=Part	4	parataxis	4:parataxis	_
15	na	to	PART	TO	_	16	mark	16:mark	_
16	go	go	VERB	VB	VerbForm=Inf	14	xcomp	14:xcomp	_
17	ahead	ahead	ADV	RB	Degree=Pos	16	advmod	16:advmod	_
18	and	and	CCONJ	CC	_	19	cc	19:cc	Discourse=contrast:176->164
19	throw	throw	VERB	VB	Person=2|VerbForm=Inf	16	conj	14:xcomp|16:conj:and	_
20	it	it	PRON	PRP	Case=Acc|Gender=Neut|Number=Sing|Person=3|PronType=Prs	19	obj	19:obj	Entity=(object-86)
21	in	in	ADP	IN	_	24	case	24:case	_
22	the	the	DET	DT	Definite=Def|PronType=Art	24	det	24:det	Entity=(object-45
23	expired	expired	ADJ	JJ	Degree=Pos	24	amod	24:amod	_
24	pile	pile	NOUN	NN	Number=Sing	19	obl	19:obl:in	Entity=object-45)|SpaceAfter=No
25	.	.	PUNCT	.	_	4	punct	4:punct	_
```
And in the following sentence, "so" is marked as ADV, but it should have the same meaning as "so that"?
```
# sent_id = GUM_interview_chomsky-20
# s_type = decl
# speaker = NoamChomsky
# text = Nevertheless he agreed, but there was a quid pro quo, namely that NATO should not expand to the east, so Russia would at least have a kind of security zone.
1	Nevertheless	nevertheless	ADV	RB	Degree=Pos	3	advmod	3:advmod	Discourse=elaboration:44->38
2	he	he	PRON	PRP	Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs	3	nsubj	3:nsubj	Entity=(person-45-Mikhail_Gorbachev)
3	agreed	agree	VERB	VBD	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	0	root	0:root	SpaceAfter=No
4	,	,	PUNCT	,	_	7	punct	7:punct	_
5	but	but	CCONJ	CC	_	7	cc	7:cc	Discourse=concession:45->44
6	there	there	PRON	EX	_	7	expl	7:expl	_
7	was	be	VERB	VBD	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	3	conj	3:conj:but	_
8	a	a	DET	DT	Definite=Ind|PronType=Art	9	det	9:det	Entity=(event-55
9	quid	quid	X	FW	_	7	nsubj	7:nsubj	_
10	pro	pro	X	FW	_	11	case	11:case	_
11	quo	quo	X	FW	_	9	nmod	9:nmod:pro	Entity=event-55)|SpaceAfter=No
12	,	,	PUNCT	,	_	18	punct	18:punct	_
13	namely	namely	ADV	RB	_	18	advmod	18:advmod	_
14	that	that	SCONJ	IN	_	18	mark	18:mark	Discourse=elaboration:46->45
15	NATO	NATO	PROPN	NNP	Abbr=Yes|Number=Sing	18	nsubj	18:nsubj	Entity=(organization-29-NATO)
16	should	should	AUX	MD	VerbForm=Fin	18	aux	18:aux	_
17	not	not	PART	RB	Polarity=Neg	18	advmod	18:advmod	_
18	expand	expand	VERB	VB	VerbForm=Inf	9	acl	9:acl:that	_
19	to	to	ADP	IN	_	21	case	21:case	_
20	the	the	DET	DT	Definite=Def|PronType=Art	21	det	21:det	Entity=(place-56
21	east	east	NOUN	NN	Number=Sing	18	obl	18:obl:to	Entity=place-56)|SpaceAfter=No
22	,	,	PUNCT	,	_	28	punct	28:punct	_
23	so	so	ADV	RB	_	28	advmod	28:advmod	Discourse=purpose:47->45
24	Russia	Russia	PROPN	NNP	Number=Sing	28	nsubj	28:nsubj	Entity=(place-53-Russia)
25	would	would	AUX	MD	VerbForm=Fin	28	aux	28:aux	_
26	at	at	ADV	IN	_	28	advmod	28:advmod	_
27	least	least	ADJ	JJS	Degree=Sup	26	fixed	26:fixed	_
28	have	have	VERB	VB	VerbForm=Inf	7	parataxis	7:parataxis	_
29	a	a	DET	DT	Definite=Ind|PronType=Art	30	det	30:det	_
30	kind	kind	NOUN	NN	Number=Sing	28	obj	28:obj	Entity=(place-57
31	of	of	ADP	IN	_	33	case	33:case	_
32	security	security	NOUN	NN	Number=Sing	33	compound	33:compound	_
33	zone	zone	NOUN	NN	Number=Sing	30	nmod	30:nmod:of	Entity=place-57)|SpaceAfter=No
34	.	.	PUNCT	.	_	3	punct	3:punct	_
```
Finally, I'm curious about the reason for tagging "so" and "therefore" as ADV? Because I can't find information about this in the guidlines. And in the discussion about the difference between "so" and "therefore" on the Internet, people usually regard them as conjunctions, that's @muchang and I thought so before.

**Comment by nschneid** [comment] 2021-07-11 14:49
I agree, the last 3 look like errors in GUM.

There is unfortunately not much documentation for English-specific details of UD tagging guidelines. Many distinctions are drawn from the [Penn Treebank tagging guidelines](https://catalog.ldc.upenn.edu/docs/LDC99T42/tagguid1.pdf), which govern the tags in the XPOS column. You can see on p. 29 that for "so", they specify RB for some instances (these should be `ADV` for UPOS) and IN for others (these should be `SCONJ`).

In two of your examples above, both the UPOS and XPOS are incorrect. I am finding [6 examples](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=60eb02f79314f&clustering=N.upos) where the UPOS and XPOS are *inconsistent*, with `SCONJ` and RB. I think these should be `ADV`.

**Comment by youyusama** [comment] 2021-07-12 03:30
Thanks. That's helpful.

**Comment by amir-zeldes** [comment] 2021-07-15 12:31
Thanks for pointing out these last few errors, I will fix them. I think at least part of the reason for tagging "therefore" as an adverb is that it is both movable ("I am therefore just gonna go ahead..."), and combinable with proper subordinating conjunctions ("if you therefore decide...."). The treatment of "so" when substitutable by "therefore" is probably by analogy to "therefore".

**Closed** 2021-08-06 18:58 UTC
